name: trenchripper
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh=1.4.0
  - cachetools
  - click
  - cudatoolkit=10.0
  - dask-jobqueue
  - dask=2.12.0
  - distributed=2.12.0
  - fastparquet
  - h5py
  - ipympl
  - ipywidgets
  - jupyter-server-proxy
  - jupyterlab
  - matplotlib
  - nbformat
  - nodejs
  - pip
  - pip:
      - pulp
      - h5py-cache
      - parse
      - nd2reader
      - opencv-python
  - pre-commit
  - pytables
  - pytorch
  - qgrid
  - scikit-image
  - scikit-learn
  - seaborn
  - tifffile
  - torchvision
